baseURL = "/"
languageCode = "en-us"
title = "Scratching With Hardware - Doku - Philipp Kohler"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Labore"
    url = "/labore/"
    weight = 2

[[menu.main]]
    name = "Projekt"
    url = "/projekt/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/labore/setup/'
  homepage_button_text = 'Setup - Erste Doku'
  homepage_image = 'https://raw.githubusercontent.com/Snoup97/swh-pkohler/master/static/img/medieninfo.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      standard  = "https://raw.githubusercontent.com/Snoup97/swh-pkohler/master/static/img/logo.png"
